Error handling
c10k/experiments pull request #2
Opened 2017-02-13 10:10 UTC by tkhurana96

2017-02-13 10:24 UTC, agauniyal commented on cpp-straight-calls-withErrorHandling/tcp-client.cpp
> +	std::mutex lockToErrorString;
should be static..

2017-02-13 10:24 UTC, agauniyal commented on cpp-straight-calls-withErrorHandling/tcp-server.cpp
> +	std::mutex lockToErrorString;
again, should be static?

2017-02-13 10:44 UTC, tkhurana96 commented
made getErrrorString() static

2017-02-14 17:21 UTC, agauniyal requested changes

2017-02-14 17:21 UTC, agauniyal commented on cpp-straight-calls-withErrorHandling/tcp-client.cpp
> +	std::string returnString(errMsg);
what if exception occurs while creation of this string?

2017-02-14 18:19 UTC, tkhurana96 commented
Added lockguard to getErrorMsg()

2017-02-14 18:38 UTC, agauniyal approved these changes

2017-02-14 18:39 UTC, merged